/**
 * SNKRS Monitors Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageType } from './image-type.model';


export interface ImageInfo { 
    readonly name?: string | null;
    readonly slug?: string | null;
    imageType?: ImageType;
    readonly requiredSpawnParameters?: Array<string> | null;
    readonly id?: string | null;
}

