/**
 * SNKRS Monitors Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageInfo } from './image-info.model';
import { ServerInstance } from './server-instance.model';


export interface ImageRuntimeInfo { 
    imageInfo?: ImageInfo;
    serverInstance?: ServerInstance;
    readonly containerId?: string | null;
    readonly status?: string | null;
    readonly state?: string | null;
    readonly createdAt?: Date;
}

