/**
 * SNKRS Monitors Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ServerInstanceStatus = 'Unknown' | 'Pending' | 'Running' | 'Stopping' | 'Stopped' | 'ShuttingDown' | 'Terminated';

export const ServerInstanceStatus = {
    Unknown: 'Unknown' as ServerInstanceStatus,
    Pending: 'Pending' as ServerInstanceStatus,
    Running: 'Running' as ServerInstanceStatus,
    Stopping: 'Stopping' as ServerInstanceStatus,
    Stopped: 'Stopped' as ServerInstanceStatus,
    ShuttingDown: 'ShuttingDown' as ServerInstanceStatus,
    Terminated: 'Terminated' as ServerInstanceStatus
};

