/**
 * SNKRS Monitors Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SupportedHostingTargets = 'Monitors' | 'Publishers';

export const SupportedHostingTargets = {
    Monitors: 'Monitors' as SupportedHostingTargets,
    Publishers: 'Publishers' as SupportedHostingTargets
};

